apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: tt
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/snk189/tt-sip-backend:598f5d4b2f33f0049d675c6c97235a17520a4e7b
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: turing-config
        - secretRef:
            name: turing-secrets
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
