apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tt
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/snk189/turingtest_gdg_sip.git
    targetRevision: dev
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: tt
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: backend
      namespace: tt
      jsonPointers:
        - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true