apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: turing-test
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/snk189/turing-test-frontend:0d2612792a09d6d54b3b3c28cd19828552f89692
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
