apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tt
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/snk189/tt-sip-frontend:f83ad223d5405931a012132b3cc57a80a6e1c5b8
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
