apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: tt
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/rasam729/tt-sip-frontend:ba9207664aa52946c5855dd16b5c4bed348ac7e6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
