apiVersion: v1
kind: ConfigMap
metadata:
  name: turing-config
  namespace: turing-test
data:
  NODE_ENV: "production"
  PORT: "3000"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  CORS_ORIGIN: "http://localhost,http://127.0.0.1,https://turing-test.local,http://turing-test.local"
