apiVersion: v1
kind: Secret
metadata:
  name: turing-secrets
  namespace: tt
type: Opaque
stringData:
  REDIS_PASSWORD: "production-redis-password"
  JWT_SECRET: "production-jwt-secret-key"
  ADMIN_SEED_USERNAME: "A"
  ADMIN_SEED_PASSWORD: "a"
